nelmio_api_doc:
  documentation:
    info:
      title: "Billing API"
      version: "1.0.0"
      description: "Документация API"
    components:
#      securitySchemes:
#        cookieAuth:
#          type: apiKey
#          in: cookie
#          name: PHPSESSID
    security:
      - cookieAuth: []
  areas:
    default:
      path_patterns:
        - ^/user-cabinet*