[www]
; отключаем access лог php-fpm
access.log = /dev/null
; или можно закомментировать, но /dev/null проще

; и можно явно включить вывод ошибок в stderr
php_admin_flag[log_errors] = on
php_admin_value[error_log] = /proc/self/fd/2
