user-cabinet-api-v1:
    prefix: /user-cabinet/
    resource: ../src/Modules/UserCabinet/Adapter/Controllers/APIv1
    type:     attribute
    defaults:
        version: 1
builderman-cabinet-v1:
    prefix: /builderman-cabinet/
    resource: ../src/Modules/BuildermanCabinet/Adapter/Api/Controllers
    type:     attribute
    defaults:
        version: 1